# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/lge/vs910/setup-makefiles.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES := \
    lge/vs910/proprietary/lib/liboncrpc.so:obj/lib/liboncrpc.so \
    lge/vs910/proprietary/lib/libnv.so:obj/lib/libnv.so \
    lge/vs910/proprietary/lib/libaudio.so:obj/lib/libaudio.so \
    lge/vs910/proprietary/lib/libv8.so:obj/lib/libv8.so

PRODUCT_COPY_FILES += \
    lge/vs910/proprietary/bin/qmuxd:system/bin/qmuxd \
    lge/vs910/proprietary/bin/hciattach:system/bin/hciattach \
    lge/vs910/proprietary/bin/rmt_storage:system/bin/rmt_storage \
    lge/vs910/proprietary/bin/netmgrd:system/bin/netmgrd \
    lge/vs910/proprietary/bin/port-bridge:system/bin/port-bridge \
    lge/vs910/proprietary/bin/rild:system/bin/rild \
    lge/vs910/proprietary/bin/thermald:system/bin/thermald \
    lge/vs910/proprietary/bin/hdmid:system/bin/hdmid \
    lge/vs910/proprietary/bin/bluetoothd:system/bin/bluetoothd \
    lge/vs910/proprietary/bin/cnd:system/bin/cnd \
    lge/vs910/proprietary/bin/mm-abl-test:system/bin/mm-abl-test \
    lge/vs910/proprietary/bin/mm-adec-omxaac-test:system/bin/mm-adec-omxaac-test \
    lge/vs910/proprietary/bin/mm-adec-omxadpcm-test:system/bin/mm-adec-omxadpcm-test \
    lge/vs910/proprietary/bin/mm-adec-omxamr-test:system/bin/mm-adec-omxamr-test \
    lge/vs910/proprietary/bin/mm-adec-omxamrwb-test:system/bin/mm-adec-omxamrwb-test \
    lge/vs910/proprietary/bin/mm-adec-omxevrc-test:system/bin/mm-adec-omxevrc-test \
    lge/vs910/proprietary/bin/mm-adec-omxmp3-test:system/bin/mm-adec-omxmp3-test \
    lge/vs910/proprietary/bin/mm-adec-omxQcelp13-test:system/bin/mm-adec-omxQcelp13-test \
    lge/vs910/proprietary/bin/mm-adec-omxwma-test:system/bin/mm-adec-omxwma-test \
    lge/vs910/proprietary/bin/mm-aenc-omxaac-test:system/bin/mm-aenc-omxaac-test \
    lge/vs910/proprietary/bin/mm-aenc-omxamr-test:system/bin/mm-aenc-omxamr-test \
    lge/vs910/proprietary/bin/mm-aenc-omxevrc-test:system/bin/mm-aenc-omxevrc-test \
    lge/vs910/proprietary/bin/mm-aenc-omxqcelp13-test:system/bin/mm-aenc-omxqcelp13-test \
    lge/vs910/proprietary/bin/mm-audio-alsa-test:system/bin/mm-audio-alsa-test \
    lge/vs910/proprietary/bin/mm-audio-ctrl-test:system/bin/mm-audio-ctrl-test \
    lge/vs910/proprietary/bin/mm-audio-native-test:system/bin/mm-audio-native-test \
    lge/vs910/proprietary/bin/mm-audio-voem_if-test:system/bin/mm-audio-voem_if-test \
    lge/vs910/proprietary/bin/mm-jpeg-dec-test:system/bin/mm-jpeg-dec-test \
    lge/vs910/proprietary/bin/mm-jpeg-enc-test:system/bin/mm-jpeg-enc-test \
    lge/vs910/proprietary/bin/mm-omx-devmgr:system/bin/mm-omx-devmgr \
    lge/vs910/proprietary/bin/mm-qcamera-test:system/bin/mm-qcamera-test \
    lge/vs910/proprietary/bin/mm-qcamera-testsuite-client:system/bin/mm-qcamera-testsuite-client \
    lge/vs910/proprietary/bin/mm-vdec-omx-test:system/bin/mm-vdec-omx-test \
    lge/vs910/proprietary/bin/mm-venc-omx-test720p:system/bin/mm-venc-omx-test720p \
    lge/vs910/proprietary/bin/mm-video-driver-test:system/bin/mm-video-driver-test \
    lge/vs910/proprietary/bin/mm-video-encdrv-test:system/bin/mm-video-encdrv-test \
    lge/vs910/proprietary/lib/libcamera.so:system/lib/libcamera.so \
    lge/vs910/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
    lge/vs910/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
    lge/vs910/proprietary/lib/libmmipl.so:system/lib/libmmipl.so \
    lge/vs910/proprietary/lib/libaudio.so:system/lib/libaudio.so \
    lge/vs910/proprietary/lib/libaudioalsa.so:system/lib/libaudioalsa.so \
    lge/vs910/proprietary/lib/liba2dp.so:system/lib/liba2dp.so \
    lge/vs910/proprietary/lib/egl/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
    lge/vs910/proprietary/lib/egl/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
    lge/vs910/proprietary/lib/egl/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
    lge/vs910/proprietary/lib/egl/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \
    lge/vs910/proprietary/lib/libgsl.so/:system/lib/libgsl.so/ \
    lge/vs910/proprietary/lib/hw/sensors.default.so:system/lib/hw/sensors.default.so \
    lge/vs910/proprietary/lib/libOmxEvrcEnc.so:system/lib/libOmxEvrcEnc.so \
    lge/vs910/proprietary/lib/libOmxAacDec.so:system/lib/libOmxAacDec.so \
    lge/vs910/proprietary/lib/libOmxQcelp13Dec.so:system/lib/libOmxQcelp13Dec.so \
    lge/vs910/proprietary/lib/libOmxAmrEnc.so:system/lib/libOmxAmrEnc.so \
    lge/vs910/proprietary/lib/libOmxAdpcmDec.so:system/lib/libOmxAdpcmDec.so \
    lge/vs910/proprietary/lib/libOmxEvrcDec.so:system/lib/libOmxEvrcDec.so \
    lge/vs910/proprietary/lib/libOmxAmrDec.so:system/lib/libOmxAmrDec.so \
    lge/vs910/proprietary/lib/libOmxAmrwbDec.so:system/lib/libOmxAmrwbDec.so \
    lge/vs910/proprietary/lib/libOmxWmaDec.so:system/lib/libOmxWmaDec.so \
    lge/vs910/proprietary/lib/libOmxQcelp13Enc.so:system/lib/libOmxQcelp13Enc.so \
    lge/vs910/proprietary/lib/libOmxMp3Dec.so:system/lib/libOmxMp3Dec.so \
    lge/vs910/proprietary/lib/libOmxAmrRtpDec.so:system/lib/libOmxAmrRtpDec.so \
    lge/vs910/proprietary/lib/libOmxAacEnc.so:system/lib/libOmxAacEnc.so \
    lge/vs910/proprietary/lib/libomx_aacdec_sharedlibrary.so:system/lib/libomx_aacdec_sharedlibrary.so \
    lge/vs910/proprietary/lib/libomx_amrdec_sharedlibrary.so:system/lib/libomx_amrdec_sharedlibrary.so \
    lge/vs910/proprietary/lib/libomx_amrenc_sharedlibrary.so:system/lib/libomx_amrenc_sharedlibrary.so \
    lge/vs910/proprietary/lib/libomx_avcdec_sharedlibrary.so:system/lib/libomx_avcdec_sharedlibrary.so \
    lge/vs910/proprietary/lib/libomx_m4vdec_sharedlibrary.so:system/lib/libomx_m4vdec_sharedlibrary.so \
    lge/vs910/proprietary/lib/libomx_mp3dec_sharedlibrary.so:system/lib/libomx_mp3dec_sharedlibrary.so \
    lge/vs910/proprietary/lib/libomx_sharedlibrary.so:system/lib/libomx_sharedlibrary.so \
    lge/vs910/proprietary/lib/libOmxCore.so:system/lib/libOmxCore.so \
    lge/vs910/proprietary/lib/libril.so:system/lib/libril.so \
    lge/vs910/proprietary/lib/libril-qc-1.so:system/lib/libril-qc-1.so \
    lge/vs910/proprietary/lib/libreference-ril.so:system/lib/libreference-ril.so \
    lge/vs910/proprietary/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
    lge/vs910/proprietary/lib/libril-qc-1.so:system/lib/libril-qc-1.so \
    lge/vs910/proprietary/lib/libril-qc-qmi-1.so:system/lib/libril-qc-qmi-1.so \
    lge/vs910/proprietary/lib/libdiag.so:system/lib/libdiag.so \
    lge/vs910/proprietary/lib/liboncrpc.so:system/lib/liboncrpc.so \
    lge/vs910/proprietary/lib/libqmi.so:system/lib/libqmi.so \
    lge/vs910/proprietary/lib/libqmiservices.so:system/lib/libqmiservices.so \
    lge/vs910/proprietary/lib/libdsm.so:system/lib/libdsm.so \
    lge/vs910/proprietary/lib/libqueue.so:system/lib/libqueue.so \
    lge/vs910/proprietary/lib/libcm.so:system/lib/libcm.so \
    lge/vs910/proprietary/lib/libmmgsdilib.so:system/lib/libmmgsdilib.so \
    lge/vs910/proprietary/lib/libgsdi_exp.so:system/lib/libgsdi_exp.so \
    lge/vs910/proprietary/lib/libgstk_exp.so:system/lib/libgstk_exp.so \
    lge/vs910/proprietary/lib/libwms.so:system/lib/libwms.so \
    lge/vs910/proprietary/lib/libnv.so:system/lib/libnv.so \
    lge/vs910/proprietary/lib/libwmsts.so:system/lib/libwmsts.so \
    lge/vs910/proprietary/lib/libpbmlib.so:system/lib/libpbmlib.so \
    lge/vs910/proprietary/lib/libdss.so:system/lib/libdss.so \
    lge/vs910/proprietary/lib/libauth.so:system/lib/libauth.so \
    lge/vs910/proprietary/lib/libqdp.so:system/lib/libqdp.so \
    lge/vs910/proprietary/lib/libidl.so:system/lib/libidl.so \
    lge/vs910/proprietary/lib/libdsutils.so:system/lib/libdsutils.so \
    lge/vs910/proprietary/lib/liboem_rapi.so:system/lib/liboem_rapi.so \
    lge/vs910/proprietary/lib/libdsi_netctrl.so:system/lib/libdsi_netctrl.so \
    lge/vs910/proprietary/lib/libnetmgr.so:system/lib/libnetmgr.so \
    lge/vs910/proprietary/lib/liboncrpc.so:system/lib/liboncrpc.so \
    lge/vs910/proprietary/lib/libpdapi.so:system/lib/libpdapi.so \
    lge/vs910/proprietary/lib/libpdsm_atl.so:system/lib/libpdsm_atl.so \
    lge/vs910/proprietary/lib/libuim.so:system/lib/libuim.so \
    lge/vs910/proprietary/lib/libgemini.so:system/lib/libgemini.so \
    lge/vs910/proprietary/lib/libcommondefs.so:system/lib/libcommondefs.so \
    lge/vs910/proprietary/lib/librpc.so:system/lib/librpc.so
